uploads = []
generated = []

[[outputs]]
id = "-4oZh4vBRaUb_gEnxPvuU"
uri = "file://MattrMindr_AI_Models.txt"
type = "text"
title = "MattrMindr AI Models by Agent"

[[outputs]]
id = "ivKP3jcbWQ9gfqtg_CWxX"
uri = "file://MattrMindr_Technical_Blueprint.rtf"
type = "unspecified"
title = "MattrMindr Technical Blueprint (.rtf)"

[[outputs]]
id = "5NFvQxcUZxtHVS2mu8YOp"
uri = "file://AWS-RDS-MIGRATION-GUIDE.md"
type = "text"
title = "AWS RDS Migration Guide"

[[outputs]]
id = "LzG-42xajpDJzND3TsVYY"
uri = "file://EC2-DEPLOYMENT-PLAN.md"
type = "text"
title = "MattrMindr EC2 Deployment Plan"
